### ISSUE TITLE
ゲーム画面へ遷移しない

### ISSUE THREAD

**Issue by LightGive** [zurachu/pong-de-ring#6]
自分の環境だけかもしれませんが、「Click to Start」→「Normal」「Extra」の選択画面には遷移しますが、両方とも選択した後「Connecting...」が表示されたまま遷移しないです。コードを読んでないので何とも言えませんが、前遊んだ時は普通に遷移していたのでアップデート周りで起きた不具合かと思います。
![test](https://user-images.githubusercontent.com/8480185/54877381-1a353680-4e61-11e9-8641-74698b6d9486.gif)

また遊びたいので修正されると嬉しいです笑

**Comment by zurachu** [comment]
私のところでも再現しました。
Android版やローカルのUnityEditorでは起こっていなかったので、再ビルド、unityroomに再アップロードしたら、改善したようですので、再度お試しいただければと思います！
前のままの場合は、ブラウザのキャッシュ飛ばしたりスーパーリロードしたりしてみてください。

最後の一文本当にありがたいですw

**Comment by LightGive** [comment]
バッチリ遊べるようになってました！(＾＾)ｂ
Android版作っておられるんですね、確かにスマホだと楽しそうですね！
1WeekGamejam過ぎたのに対応有難うございます！

遊ばせてもらいますね〜！
